
name: Djuntar
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  sending-email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Create attachment
        run: echo "This is the content of my attachment" > attachment.txt

      - name: Upload attachment
        uses: actions/upload-artifact@v2
        with:
          name: attachment
          path: attachment.txt
          
      - name: Send email
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Message from github actions.
          to: ing.saganome@gmail.com
          from: ing.saganome@gmail.com
          secure: true
          body: prueba
          contentType: text/html
          attachments: ${{ runner.temp }}/attachment/attachment.txt
