name: Adjuntos
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  sending-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v1.3.0
        with:
          host: smtp.gmail.com
          # Optional port (defaults to 465)
          port: 465
          account: ${{secrets.USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: devellany
          from: ing.saganome@gmail.com
          to: ing.saganome@gmail.com
          subject: Saganome
          body: your messages.
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          #attachments: '[{"path":"README.md"}]'

