name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  sending-email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Send email
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ing.saganome@gmail.com
          password: xmfxrdkmjuxswaxl
          subject: Message from github actions.
          to: ing.saganome@gmail.com
          from: ing.saganome@gmail.com
          secure: true
          body: workflow for completed successfully!
